### ISSUE TITLE
Getting Credentials ready for L5

### ISSUE THREAD

**Issue by MartijnThomas** [BootstrapCMS/Credentials#22]
Hi Graham, No pressure but I was wondering when you will get your credenials package L5 ready?

This one is still struggeling with the package method ;) and probably implementing orchestra's config solution.

Again no pressure, just wondering if you could give an estimate :)

**Comment by GrahamCampbell** [comment]
It currently works with an older version of L5 (my GrahamCampbell/framework fork is locked at that old version if you want an easy way to use it). I actually have a local version that's partially working with the newest L5. I was planning to finish it off today or tomorrow actually. :)

**Comment by GrahamCampbell** [comment]
> and probably implementing orchestra's config solution.

Yeh, It'll be the same deal that I've done with my other packages. :)

**Comment by rweas** [comment]
@GrahamCampbell Cool I was trying to use this.

**Comment by GrahamCampbell** [comment]
Ok, now that all my other laravel packages are working on the current L5, then I'm starting on this stuff. First commit: https://github.com/BootstrapCMS/sentry/commit/caf5926ba8a62bcbda8173a470b5d4585503e9e5.

**Comment by GrahamCampbell** [comment]
And c8cdffa9d52c7bf11de431bef85ccaa3d7b70b26 updates this repo. I'll be updating the actual cms repo tomorrow.

**Comment by rweas** [comment]
@GrahamCampbell Cool! Thanks!

**Comment by GrahamCampbell** [comment]
Everything's updated now, and seems to be working on my tests. :)
