### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by assoft** [BootstrapCMS/Credentials#23]
<code>
➜  credentials  composer update

Loading composer repositories with package information

Updating dependencies (including require-dev)

<b>Your requirements could not be resolved to an installable set of packages.</b>

  Problem 1
    - The requested package graham-campbell/credentials could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

➜  credentials  php -v
<b>PHP 5.5.20 (cli) (built: Jan  2 2015 19:26:12)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies</b>
</code>

**Comment by GrahamCampbell** [comment]
Use `@dev` or lower your overall minimum stability.
