### ISSUE TITLE
Couldn't find stable package.

### ISSUE THREAD

**Issue by rweas** [BootstrapCMS/Credentials#24]
[InvalidArgumentException]
  Could not find package graham-campbell/credentials at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

I just tried to install it in a brand new Laravel installation and this happened. :/

**Comment by GrahamCampbell** [comment]
Yeh, you have to do that of course - look at the releases - I only have alpha tags, and there is no tag for the L5 version yet (0.4).

**Comment by rweas** [comment]
Oh. I didn't know how to use @dev in composer. Thanks!

**Comment by rweas** [comment]
OK now I have a new error: 

graham-campbell/credentials 0.4.x-dev requires cartalyst/sentry ~3.0 -> no matching package found.

**Comment by GrahamCampbell** [comment]
https://github.com/BootstrapCMS/Credentials/blob/master/composer.json#L62
