### ISSUE TITLE
Bad require in composer.json

### ISSUE THREAD

**Issue by mdcockfi** [BootstrapCMS/Credentials#26]
You are still requireing cartalyst/sentry": "~3.0, this has been removed from the BootstrapCMS composer.json.

**Comment by GrahamCampbell** [comment]
I don't see where the issue is?

**Comment by mdcockfi** [comment]
Okay actually you have changed the BootstrapCMS/CMS composer.json to require your fork "graham-campbell/credentials": "0.4.*", and it installs just fine. I am getting the following error when I try to install BootstrapCMS/Credentials:

  Problem 1
    - Installation request for graham-campbell/credentials 0.4.* -> satisfiable by graham-campbell/credentials[0.4.x-dev].
    - graham-campbell/credentials 0.4.x-dev requires cartalyst/sentry ~3.0 -> no matching package found.

**Comment by GrahamCampbell** [comment]
You need to add:

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/BootstrapCMS/sentry"
        }
    ],
```

to your composer.json file.

**Comment by GrahamCampbell** [comment]
> Okay actually you have changed the BootstrapCMS/CMS composer.json

No changes need to be made to that file. It works out of the box, as proved by travis.

**Comment by mdcockfi** [comment]
Sorry for the confusion. Yes, this step is missing from the installation 
instructions.

**Comment by hackel** [comment]
I just figured this out myself after much frustration and trial-and-error.  Is this a bug in composer that it is not using the repositories defined in BootstrapCMS/Credentials composer.json?  I don't remember having this issue the first time I used this package, which had installed an older revision of BootstrapCMS/sentry that refused to update without adding the repo to my own composer.json.

**Comment by GrahamCampbell** [comment]
>  Is this a bug in composer that it is not using the repositories defined in BootstrapCMS/Credentials composer.json? 

You need to add "repositories" to your main composer.json because composer is retarded.
