### ISSUE TITLE
Sentry 3.0 doesn't exist...

### ISSUE THREAD

**Issue by rweas** [BootstrapCMS/Credentials#27]
https://github.com/BootstrapCMS/Credentials/blob/master/composer.json#L32

https://packagist.org/packages/cartalyst/sentry

I might be doing something wrong but packagist isn't showing a 3.0 branch.

Thanks for making this package!

**Comment by rweas** [comment]
https://github.com/rweas/Credentials/blob/master/composer.json#L32

This seems to work so far.

**Comment by rweas** [comment]
I can create a PR if you would like.

**Comment by GrahamCampbell** [comment]
You need to use my fork of sentry. Packagist says you shouldn't repackage forks, so the name remains the same.

**Comment by GrahamCampbell** [comment]
Also, your suggestion on your fork is incorrect.

**Comment by rweas** [comment]
Thanks! I saw your fork but didn't think to use it.
