### ISSUE TITLE
cartalyst/sentry ~3.0 > no matching package found.

### ISSUE THREAD

**Issue by c0m3nk** [BootstrapCMS/Credentials#28]
when run composer update, getting this error

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for graham-campbell/credentials dev-master -> satisfiable by graham-campbell/credentials[dev-master].
    - graham-campbell/credentials dev-master requires cartalyst/sentry ~3.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by GrahamCampbell** [comment]
Duplicate. You need to add our sentry for you your "repositories" section of your composer.json for now.
