### ISSUE TITLE
PaginateRepositoryTrait isFirstPage Argument is wrong Class

### ISSUE THREAD

**Issue by popungco** [BootstrapCMS/Credentials#32]
I encounter error when posts are empty.
<code>
Argument 1 passed to GrahamCampbell\BootstrapCMS\Repositories\PostRepository::isFirstPage() must be an instance of GrahamCampbell\Credentials\Repositories\Paginator, instance of Illuminate\Pagination\LengthAwarePaginator given, called in /var/www/html/pblog/vendor/graham-campbell/credentials/src/Repositories/PaginateRepositoryTrait.php on line 48 and defined 
</code>

Method isFirstPage argument is Paginator now.
It must be LengthAwarePaginator.

<code>PaginateRepositoryTrait.php</code>
```php
    /**
     * Is the current page the first page?
     *
     * @param \Illuminate\Pagination\Paginator $paginator
     *
     * @return bool
     */
    protected function isFirstPage(LengthAwarePaginator $paginator)
    {
        return ($paginator->currentPage() === 1);
    }

**Comment by GrahamCampbell** [comment]
Fixed.
