### ISSUE TITLE
Expose properties of the user model

### ISSUE THREAD

**Issue by qrokodial** [BootstrapCMS/Credentials#34]
right now things like `first_name` and `last_name` are hardcoded in. it would be nice to have a way to be able to add other properties like `username` and perhaps remove properties as well (not every application would want/need the user's real name, for example).

it's easy enough to write our own migrations, but since these properties are hardcoded, you'd have to edit the actual source code in order to tweak things to suit your needs.

**Comment by GrahamCampbell** [comment]
I'm open to PRs if you have a clean way to deal with this. :)
